'use client';

import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { generateAuditReport } from '@/app/actions/audit';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

function formatPayloadForPDF(val: string | null) {
  if (!val || val === 'null' || val === 'N/A' || val === 'DELETED') return val || '';
  try {
    const parsed = JSON.parse(val);
    if (typeof parsed === 'object' && parsed !== null) {
      const ignoredKeys = ['id', 'created_at', 'updated_at', 'deleted_at', 'icon', 'color', 'count', '_count', 'department_id', 'position_id', 'password_hash'];
      const entries = Object.entries(parsed).filter(
        ([k, v]) => !ignoredKeys.includes(k) && v !== null && v !== '' && typeof v !== 'object'
      );
      if (entries.length === 0) return 'No Attributes Changed';
      
      return entries
        .map(([k, v]) => `${k.replace(/_/g, ' ').toUpperCase()}: ${v}`)
        .join('\n');
    }
    return String(parsed);
  } catch(e) {
    return val;
  }
}

export default function GenerateComplianceReportButton() {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownload = async () => {
    setIsGenerating(true);
    const toastId = toast.loading('Compiling compliance data...');

    try {
      const response = await generateAuditReport();

      if (response.success && response.activeLogs && response.accessLogs) {
        const { activeLogs, accessLogs, auditorName } = response;
        const currentDate = new Date().toLocaleDateString();

        const doc = new jsPDF('l', 'pt', 'a4');
        doc.setFont('helvetica');
        const pageWidth = doc.internal.pageSize.getWidth();
        
        // --- Header (Branding) ---
        doc.setFontSize(18);
        doc.text("Salarize Enterprise Security - Official Compliance Report", pageWidth / 2, 40, { align: "center" });
        
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated by: ${auditorName} | Date: ${currentDate}`, 40, 60);
        doc.text("Scope: Reporting Period: Last 30 Days", 40, 75);

        // --- Section 1: Executive Summary ---
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text("Executive Summary", 40, 100);
        
        doc.setFontSize(10);
        doc.text(`Active Operational Records: ${activeLogs.length}`, 40, 115);
        doc.text(`System Access Events: ${accessLogs.length}`, 40, 130);

        // --- Section 2: Active Operational History ---
        doc.text("Active Operational History", 40, 160);

        autoTable(doc, {
          startY: 170,
          theme: 'grid',
          head: [['Timestamp', 'Actor', 'Action', 'Target', 'Old Value', 'New Value']],
          body: activeLogs.map((log: any) => {
            const isCreate = log.action.includes('CREATE') || log.action.includes('ADDED');
            const isDelete = log.action.includes('DELETE') || log.action.includes('ARCHIVE');
            
            const oldVal = isCreate ? '[None]' : formatPayloadForPDF(log.old_value);
            const newVal = isDelete ? '[DELETED]' : formatPayloadForPDF(log.new_value);

            return [
              new Date(log.timestamp).toLocaleString(),
              log.admin_name,
              log.action,
              log.target_employee || 'N/A',
              oldVal,
              newVal
            ];
          }),
          headStyles: { fillColor: [109, 40, 217] }, // Primary purple
          styles: { font: 'helvetica', fontSize: 9, cellPadding: 4, overflow: 'linebreak', valign: 'top' },
          columnStyles: {
            0: { cellWidth: 80 },
            1: { cellWidth: 70 },
            2: { cellWidth: 110 },
            3: { cellWidth: 90 },
            4: { cellWidth: 220 },
            5: { cellWidth: 220 }
          }
        });

        // --- Section 3: System Access Logs ---
        const finalY = (doc as any).lastAutoTable.finalY || 170;
        
        if (finalY > doc.internal.pageSize.getHeight() - 100) {
          doc.addPage();
          doc.text("System Access Logs", 40, 40);
          autoTable(doc, {
            startY: 50,
            theme: 'grid',
            head: [['Timestamp', 'Actor', 'Action', 'Target', 'Details']],
            body: accessLogs.map((log: any) => [
              new Date(log.timestamp).toLocaleString(),
              log.admin_name,
              log.action,
              log.target_employee || 'N/A',
              log.old_value === 'null' ? 'N/A' : (log.old_value || 'N/A')
            ]),
            headStyles: { fillColor: [225, 29, 72] }, // Muted red/rose
            styles: { font: 'helvetica', fontSize: 9, cellPadding: 4, overflow: 'linebreak', valign: 'top' },
            columnStyles: {
              0: { cellWidth: 100 },
              1: { cellWidth: 80 },
              2: { cellWidth: 120 },
              3: { cellWidth: 90 },
              4: { cellWidth: 380 } // Wider for landscape
            }
          });
        } else {
          doc.text("System Access Logs", 40, finalY + 30);
          autoTable(doc, {
            startY: finalY + 40,
            theme: 'grid',
            head: [['Timestamp', 'Actor', 'Action', 'Target', 'Details']],
            body: accessLogs.map((log: any) => [
              new Date(log.timestamp).toLocaleString(),
              log.admin_name,
              log.action,
              log.target_employee || 'N/A',
              log.old_value === 'null' ? 'N/A' : (log.old_value || 'N/A')
            ]),
            headStyles: { fillColor: [225, 29, 72] }, // Muted red/rose
            styles: { font: 'helvetica', fontSize: 9, cellPadding: 4, overflow: 'linebreak', valign: 'top' },
            columnStyles: {
              0: { cellWidth: 100 },
              1: { cellWidth: 80 },
              2: { cellWidth: 120 },
              3: { cellWidth: 90 },
              4: { cellWidth: 380 }
            }
          });
        }

        // --- Section 4: Auditor Sign-Off Block ---
        const pageHeight = doc.internal.pageSize.getHeight();
        let signOffY = (doc as any).lastAutoTable.finalY + 40;
        
        if (signOffY > pageHeight - 60) {
          doc.addPage();
          signOffY = 40;
        }

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text("I hereby certify that this report accurately reflects the immutable audit logs of the Salarize System.", 40, signOffY);
        doc.text("Auditor Signature: ___________________________          Date: ___________", 40, signOffY + 30);

        // Save PDF
        doc.save(`Salarize_Audit_Report_${new Date().toISOString().split('T')[0]}.pdf`);

        toast.success('Compliance Report PDF generated successfully.', { id: toastId });
      } else {
        toast.error(response.message || 'Failed to generate report.', { id: toastId });
      }
    } catch (error) {
      console.error(error);
      toast.error('An error occurred during report generation.', { id: toastId });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={isGenerating}
      className="flex items-center space-x-2 px-4 py-2 text-sm font-medium text-violet-700 bg-white border-2 border-violet-200 hover:border-violet-600 hover:bg-violet-50 rounded-lg transition-all duration-200 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
    >
      {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
      <span>Generate Compliance Report</span>
    </button>
  );
}
