'use client';

import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { generateAuditReport } from '@/app/actions/audit';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function GenerateComplianceReportButton() {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownload = async () => {
    setIsGenerating(true);
    const toastId = toast.loading('Compiling compliance data...');

    try {
      const response = await generateAuditReport();

      if (response.success && response.logs) {
        const { logs, auditorName } = response;
        const currentDate = new Date().toLocaleDateString();

        const doc = new jsPDF();
        doc.setFont('helvetica');
        const pageWidth = doc.internal.pageSize.width;
        
        // --- Header (Branding) ---
        doc.setFontSize(18);
        doc.text("Salarize Enterprise Security - Official Compliance Report", pageWidth / 2, 20, { align: "center" });
        
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated by: ${auditorName} | Date: ${currentDate}`, 14, 30);
        doc.text("Scope: Reporting Period: Last 30 Days", 14, 36);

        // --- Section 1: Executive Summary ---
        const criticalAnomalies = logs.filter((log: any) => 
          ['DELETE EMPLOYEE', 'CLEARED_LOGS', 'UPDATE SALARY'].includes(log.action)
        ).length;
        
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text("Executive Summary", 14, 46);
        
        doc.setFontSize(10);
        doc.text(`Total Logged Events: ${logs.length}`, 14, 54);
        doc.text(`Critical Security Anomalies: ${criticalAnomalies}`, 14, 60);
        
        const systemStatus = criticalAnomalies > 0 ? "Review Required" : "Compliant";
        doc.text(`System Status: `, 14, 66);
        if (systemStatus === "Compliant") {
          doc.setTextColor(0, 128, 0);
        } else {
          doc.setTextColor(255, 0, 0);
        }
        doc.text(systemStatus, 42, 66);
        doc.setTextColor(0);

        // --- Section 2: High-Risk Action Log ---
        const highRiskLogs = logs.filter((log: any) => 
          ['CLEARED_LOGS', 'DELETE EMPLOYEE', 'UPDATE SALARY', 'REVOKE ROLE'].includes(log.action)
        );

        doc.text("High-Risk Action Log", 14, 78);

        autoTable(doc, {
          startY: 82,
          head: [['Timestamp', 'Actor', 'Action', 'Target', 'Old Value', 'New Value']],
          body: highRiskLogs.map((log: any) => [
            new Date(log.timestamp).toLocaleString(),
            log.admin_name,
            log.action,
            log.target_employee || 'N/A',
            log.old_value || '',
            log.new_value || ''
          ]),
          headStyles: { fillColor: [225, 29, 72] }, // Muted red/rose
          styles: { font: 'helvetica', fontSize: 8, cellPadding: 4, overflow: 'linebreak' },
          columnStyles: {
            4: { cellWidth: 35 },
            5: { cellWidth: 35 }
          }
        });

        // --- Section 3: Routine Operations Log ---
        const routineLogs = logs.filter((log: any) => 
          !['CLEARED_LOGS', 'DELETE EMPLOYEE', 'UPDATE SALARY', 'REVOKE ROLE'].includes(log.action)
        );

        const finalY = (doc as any).lastAutoTable.finalY || 82;
        doc.text("Routine Operations Log", 14, finalY + 10);

        autoTable(doc, {
          startY: finalY + 14,
          head: [['Timestamp', 'Actor', 'Action', 'Target', 'Details']],
          body: routineLogs.map((log: any) => [
            new Date(log.timestamp).toLocaleString(),
            log.admin_name,
            log.action,
            log.target_employee || 'N/A',
            log.new_value ? 'See System' : 'N/A'
          ]),
          headStyles: { fillColor: [109, 40, 217] }, // Primary purple
          styles: { font: 'helvetica', fontSize: 8, cellPadding: 4, overflow: 'linebreak' }
        });

        // --- Section 4: Auditor Sign-Off Block ---
        const pageHeight = doc.internal.pageSize.height;
        let signOffY = (doc as any).lastAutoTable.finalY + 20;
        
        // Ensure we have enough space for text + 30px gap + signature
        if (signOffY > pageHeight - 50) {
          doc.addPage();
          signOffY = 20;
        }

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text("I hereby certify that this report accurately reflects the immutable audit logs of the Salarize System.", 14, signOffY);
        doc.text("Auditor Signature: ___________________________          Date: ___________", 14, signOffY + 30);

        // Save PDF
        doc.save(`Salarize_Audit_Report_${new Date().toISOString().split('T')[0]}.pdf`);

        toast.success('Compliance Report PDF generated successfully.', { id: toastId });
      } else {
        toast.error(response.message || 'Failed to generate report.', { id: toastId });
      }
    } catch (error) {
      console.error(error);
      toast.error('An error occurred during report generation.', { id: toastId });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={isGenerating}
      className="flex items-center space-x-2 px-4 py-2 text-sm font-medium text-violet-700 bg-white border-2 border-violet-200 hover:border-violet-600 hover:bg-violet-50 rounded-lg transition-all duration-200 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
    >
      {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
      <span>Generate Compliance Report</span>
    </button>
  );
}
